version: "3"
services:
  base_url:
    image: monyslim/baseurl:1
    restart: always
    depends_on:
      - mysql
    ports:
      - 90:80

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: newblog
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password