name: Deployment Workflow
on:
  push:
    branches:
      - main

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: preparation
        run: echo "Preparing to deploy ..."
    
      - name: checks out the repository
        uses: actions/checkout@v4
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
            # Slack channel id, channel name, or user id to post message.
            # See also: https://api.slack.com/methods/chat.postMessage#channels
            # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
            channel-id: 'C06RC5B1U5S'
            # For posting a simple plain text message
            slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      
      - name: "Logs into docker"
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Build our code"
        env:
          IMAGE_NAME: roller102
          VERSION: latest
          USERNAME: abatan
        run: |
            docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
            docker push $USERNAME/$IMAGE_NAME:$VERSION